#!/bin/sh
date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s" >> /tmp/o3x.log
echo $0 >> /tmp/o3x.log

if [ "$(uname -r | awk -F '.' '{print $1;}')" -lt 13 ] ; then
	kernelextensionsdir=$3System/Library/Extensions
else
	kernelextensionsdir=$3Library/Extensions
	if [ ! -d $3Library/Extensions/zfs.kext/ ] ; then
		kernelextensionsdir=$3System/Library/Extensions
	fi
fi

if [ $(/usr/sbin/kextstat -b net.lundman.zfs | wc -l) -gt 1 ] ; then
	printf "\nUnloading zfs.kext...\n"
	/sbin/kextunload -b net.lundman.zfs
fi
if [ $(/usr/sbin/kextstat -b net.lundman.spl | wc -l) -gt 1 ] ; then
	printf "\nUnloading spl.kext...\n"
	/sbin/kextunload -b net.lundman.spl
fi

printf "\nTouching %s\n" "${kernelextensionsdir}"
/usr/bin/touch "${kernelextensionsdir}"

# HUP kextd
/usr/bin/killall -HUP kextd

# Load kext
printf "\nLoading spl.kext...\n"
/sbin/kextload "${kernelextensionsdir}/spl.kext"
printf "\nLoading zfs.kext...\n"
/sbin/kextload -d "${kernelextensionsdir}/spl.kext" "${kernelextensionsdir}/zfs.kext"
